name: Kyanite CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  # In the future if we want to run linting/tests using the node matrix to cover multiple node versions we can add this to each job.
  # If we want to run a matrix, this will probably have to live inside each job:
  # strategy:
  #   matrix:
  #     node-version: [12.x, 14.x]
  # - name: Use Node.js ${{ matrix.node-version }}
  #   uses: actions/setup-node@v2
  #   with:
  #     node-version: ${{ matrix.node-version }}
  # TODO: Maybe it's worth setting up a repo for composite actions? We can move reusable/bulk jobs to this repo and use them in all our other actions

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check node_module Cache
      id: node-module-cache
      uses: actions/cache@v2
      with:
          path: |
              node_modules
              */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.node-module-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Test
      run: npm run test:cov
    - name: Run Report
      run: npm run report
    - name: Check Coverage
      run: npm run check-cov
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.lcov
        name: pf-tests
        flags: unittests
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check node_module Cache
      id: node-module-cache
      uses: actions/cache@v2
      with:
          path: |
              node_modules
              */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.node-module-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Lint
      run: npm run lint
